import json, os, re

f = open("mapa-virtual.json")
bd = json.load(f)
f.close()
cidades = bd["cidades"]
lig = bd["ligacoes"]

# parsing the xml text files
for c in cidades:
    f = open('cidadesSite/' + str(c['id']) + '.html','w+')

    preHTML = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <title>Cidades de Portugal</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="w3.css">
        <meta charset="utf-8"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-green">
                <h3>Cidade: {c['nome']}</h3>
            </header>
        </div>
    """

    posHTML = f"""
        <div>
            <footer class="w3-container w3-green">
                <h2>
                    <a href="http://localhost:7777/">
                    Voltar para a página principal</a>
                </h2>
                <h5>Generated by CidadedePt::EngWeb2024::A96351</h5>
            </footer>
        </div>
    </body>
    </html>
    """

    conteudo = f"""
    <h2>População: {c['população']}</h2>
    <h2>Descrição: {c['descrição']}</h2>
    <h2>Distrito: {c['distrito']}</h2>
    """

    for l in lig:
        if l['origem'] == c['id']:
            destino_id = l['destino']
            for cid in cidades:
                if cid['id'] == destino_id:
                    destino_nome = cid['nome']

            conteudo += f"""<li><a href="http://localhost:7777/{l['destino']}.html">
                    {destino_nome} | {l['distância']} km</a> </li>
                    """

    pagHTML = preHTML + conteudo + posHTML
    f.write(pagHTML)
    f.close