import json
import unicodedata

def normalize(s):
    # Normalize the string and encode to ASCII after removing diacritics
    return ''.join(c for c in unicodedata.normalize('NFD', s)
                   if unicodedata.category(c) != 'Mn')

def chaveOrd(cidade):
    return normalize(cidade['nome'])

f = open("mapa-virtual.json")
bd = json.load(f)
f.close()
cidades = bd["cidades"]

cidades.sort(key = chaveOrd)

preHTML = """
<!DOCTYPE html>
<html>

<head>
    <title>Cidades de Portuga</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="w3.css">
    <meta charset="utf-8"/>
</head>

<body>

    <div class="w3-card-4">

        <header class="w3-container w3-green">
            <h3>Cidades de Portugal</h3>
        </header>

        <div class="w3-container">
            <ul class="w3-ul w3-card-4" style="width:100%">
"""

posHTML = """
            </ul>
        </div>

        <footer class="w3-container w3-green">
            <h5>Generated by CidadesdePt::EngWeb2024::A96351</h5>
        </footer>

    </div>

</body>

</html>
"""

conteudo = ""

for c in cidades: # r[0] -> número ; r[1] -> nome
    conteudo += f"""
                <li>
                    <a href="http://localhost:7777/{c['id']}.html">
                    {c['nome']}</a>
                </li>
                """


pagHTML = preHTML + conteudo + posHTML

f = open('cidadesSite/index.html', 'w+', encoding='utf-8')
f.write(pagHTML)
f.close