//---------------------- Composers ---------------------------
// Composers List Page
exports.composersListPage = function (slist, d) {
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Composers</title>
        </head>
        <body>
            <div class="w3-card-4">

                <header class="w3-container w3-teal">
                    <h1>Composer List
                    <a class="w3-btn w3-round w3-grey" href="/compositores/registo">+</a>
                    </h1>
                    
                </header>
        
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th><th>Nome</th><th>Periodo</th>
                            <th>Actions</th>
                        </tr>
                `
    for (let i = 0; i < slist.length; i++) {
        pagHTML += `
                <tr>
                    <td>${slist[i].id}</td>
                    <td>
                        <a href="/compositores/${slist[i].id}">
                            ${slist[i].nome}
                        </a>
                    </td>
                    <td>
                        <a href="/periodos/${slist[i].periodo}">
                            ${slist[i].periodo}
                        </a>
                    </td>
                    <td>
                        [<a href="/compositores/edit/${slist[i].id}">Edit</a>][<a href="/compositores/delete/${slist[i].id}">Delete</a>]
                    </td>
                </tr>
        `
    }

    pagHTML += `
            </table>
            </div>
                <footer class="w3-container w3-blue">
                    <h5>Generated by a96351::EngWeb2024 in ${d} - [<a href="/">Return</a>]</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}


exports.composerFormPage = function (d) {
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Composer Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Composer Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id"/>
                        <label>Name</label>
                        <input class="w3-input w3-round" type="text" name="nome"/>
                        <label>Bio</label>
                        <input class="w3-input w3-round" type="text" name="bio"/>
                        <label>Data de Nascimento</label>
                        <input class="w3-input w3-round" type="text" name="dataNasc"/>
                        <label>Data de Óbito</label>
                        <input class="w3-input w3-round" type="text" name="dataObito"/>
                        <label>Período</label>
                        <input class="w3-input w3-round" type="text" name="periodo"/>
                    </fieldset>

                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by a96351::EngWeb2024 in ${d} - [<a href="/compositores">Return</a>]</h5>
                </footer>
            
            </div>
    `
}

exports.composerFormEditPage = function (a, d) {
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Composer Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Composer Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id" readonly value="${a.id}"/>
                        <label>Nome</label>
                        <input class="w3-input w3-round" type="text" name="nome" value="${a.nome}"/>
                        <label>Bio</label>
                        <input class="w3-input w3-round" type="text" name="bio" value="${a.bio}"/>
                        <label>DataNasc</label>
                        <input class="w3-input w3-round" type="text" name="DataNasc" value="${a.dataNasc}"/>
                        <label>DataObito</label>
                        <input class="w3-input w3-round" type="text" name="DataObito" value="${a.dataObito}"/>
                        <label>Periodo</label>
                        <input class="w3-input w3-round" type="text" name="Periodo" value="${a.periodo}"/>
                    </fieldset>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by a96351::EngWeb2024 in ${d} - [<a href="/compositores">Return</a>]</h5>
                </footer>
            
            </div>
    `
    return pagHTML
}

// Composer Page
exports.composerPage = function (composer, d) {
    var pagHTML = `
    <html>
    <head>
        <title>Composer: ${composer.id}</title>
        <meta charset="utf-8"/>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>Composer ${composer.id}</h1>
            </header>

            <div class="w3-container">
                <ul class="w3-ul w3-card-4" style="width:50%">
                    <li><b>Nome: </b> ${composer.nome}</li>
                    <li><b>Biografia: </b> ${composer.bio}</li>
                    <li><b>Data de Nascimento: </b> ${composer.dataNasc}</li>
                    <li><b>Data de Óbito: </b> ${composer.dataObito}</li>
                    <li>
                        <b>Periodo: </b>
                        <a href="/periodos/${composer.periodo}">
                            ${composer.periodo}
                        </a>
                    </li>
                </ul>
            </div>
            
            <footer class="w3-container w3-teal">
                <address>Generated by a96351::EngWeb2024 in em ${d} - [<a href="/compositores">Return</a>]</address>
            </footer>
        </div>
    </body>
    </html>
    `
    return pagHTML
}

//---------------------- Periodos ---------------------------
// Periodos List Page
exports.periodosListPage = function (slist, d) {
    var pagHTML = `
    <html>
    <head>
        <meta charset="UTF-8"/>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
        <title>Periodos</title>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>Periodos List
                <a class="w3-btn w3-round w3-grey" href="/periodos/registo">+</a>
                </h1>
            </header>
        
            <div class="w3-container">
                <table class="w3-table-all">
                    <tr>
                        <th>Periodo</th><th>Desc</th><th>Actions</th>
                    </tr>
            `
    for (let i = 0; i < slist.length; i++) {
        pagHTML += `
                <tr>
                    <td>
                        <a href="/periodos/${slist[i].id}">
                            ${slist[i].id}
                        </a>
                    </td>
                    <td>
                        ${slist[i].desc}
                    </td>
                    <td>
                        [<a href="/periodos/edit/${slist[i].id}">Edit</a>][<a href="/periodos/delete/${slist[i].id}">Delete</a>]
                    </td>
                </tr>
        `
    }

    pagHTML += `
            </table>
            </div>
                <footer class="w3-container w3-blue">
                    <h5>Generated by a96351::EngWeb2024 in ${d} - [<a href="/">Return</a>]</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}

// Periodo Form Page
exports.periodoFormPage = function (d, list = []) {
    // Dynamically generate list HTML if list is not empty
    let listHTML = '';
    if (list.length > 0) {
        listHTML = `
            <ul class="w3-ul">
                ${list.map(item => `<li>${item}</li>`).join('')}
            </ul>
        `;
    }

    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Período Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Período Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Nome</label>
                        <input class="w3-input w3-round" type="text" name="id"/>
                        <label>Desc</label>
                        <input class="w3-input w3-round" type="text" name="desc"/>       
                    </fieldset>
                    ${listHTML} <!-- This will insert the list if it's not empty -->
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by a96351::EngWeb2024 in ${d} - [<a href="/compositores">Return</a>]</h5>
                </footer>
            
            </div>
        </body>
    </html>
    `;
}

// Periodo form edit page
exports.periodoFormEditPage = function (a, d) {
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Período Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Período Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id" readonly value="${a.id}"/>
                        <label>Desc</label>
                        <input class="w3-input w3-round" type="text" name="desc" value="${a.desc}"/>

                        ${a.list.map(compositor => `<input type="hidden" name="list" value="${compositor}"/>`).join("")}

                    </fieldset>

                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by a96351::EngWeb2024 in ${d} - [<a href="/periodos">Return</a>]</h5>
                </footer>
            
                </div>
    `
    return pagHTML
}


// Periodo Page
exports.periodoPage = function (periodo, d) {
    var pagHTML = `
    <html>
    <head>
        <meta charset="UTF-8"/>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
        <title>Periodos</title>
    </head>
    <body>

        <div class="w3-card-4">

            <header class="w3-container w3-teal">
            <h1>Período ${periodo.id}</h1>
            </header>
        </div>`

    if (periodo.list) {
        pagHTML += `
        <div class="w3-container">`

        periodo.list.forEach(per => {
            pagHTML += `
                        <tr><a href='/compositores/${per}'>${per}</a></tr><br>`
        })
        pagHTML += `</div>
        `} 
        pagHTML += `
          
        </div> 
                
        <footer class="w3-container w3-teal">
        <address>Generated by a96351::EngWeb2024 in ${d} - [<a href="/periodos">Return</a>]</address>
    </footer>
      </body>
  </html>
    `
        return pagHTML
    }


    // -------------- Error Treatment ------------------------------
    exports.errorPage = function (errorMessage, d) {
        var pagHTML = `
    <html>
    <head>
        <title>Error</title>
        <meta charset="utf-8"/>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>Error</h1>
            </header>

            <div class="w3-container">
                <p>${d}: Error: ${errorMessage}</p>
            </div>
            
            <footer class="w3-container w3-teal">
                <address>Generated by a96351::EngWeb2024 in ${d} - [<a href="/periodos">Return</a>]</address>
            </footer>
        </div>
    </body>
    </html>
    `
        return pagHTML
    }