import json

def chaveOrd(rua):
    return rua['rua']['meta']['nome']

f = open("combined.json")
bd = json.load(f)
f.close()

bd.sort(key = chaveOrd)

preHTML = """
<!DOCTYPE html>
<html>

<head>
    <title>Ruas de Braga</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="w3.css">
    <meta charset="utf-8"/>
</head>

<body>

    <div class="w3-card-4">

        <header class="w3-container w3-green">
            <h3>Ruas de Braga</h3>
        </header>

        <div class="w3-container">
            <ul class="w3-ul w3-card-4" style="width:50%">
"""

posHTML = """
            </ul>
        </div>

        <footer class="w3-container w3-green">
            <h5>Generated by EMDApp::EngWeb2024::A96351</h5>
        </footer>

    </div>

</body>

</html>
"""

conteudo = ""

for r in bd:
    conteudo += f"""
                <li>
                    <a href="{r['rua']['meta']['número']}.html">
                    {r['rua']['meta']['nome']}</a>
                </li>
                """


pagHTML = preHTML + conteudo + posHTML

f = open('./ruasSite/index.html', 'w')
f.write(pagHTML)
f.close

print("Created")